version: '3'

services:
  foody_app:
    build: ./config/docker
    container_name: foody_app
    environment:
      - LOCAL_USER_ID=$USER_ID
      - LOCAL_GROUP_ID=$GROUP_ID
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    command: yarn start
    ports:
      - 3339:3000
      - 3340:1337
    volumes:
      - .:/app
