version: '3.4'

x-common-variables: &common-variables
  LOCAL_USER_ID: $USER_ID
  LOCAL_GROUP_ID: $GROUP_ID
  NODE_ENV: production

services:
  foody_app:
    build: ./config/docker
    container_name: foody_app
    environment:
      <<: *common-variables
    command: yarn start
    ports:
      - 3339:3000
      - 3340:1337
    volumes:
      - .:/app
